require('lze').load {
  {
    'which-key.nvim',
    event = 'DeferredUIEnter',
    after = function()
      require('which-key').setup {
        icons = {
          mappings = false,
          keys = vim.g.have_nerd_font and {} or {
            Up = '<Up> ',
            Down = '<Down> ',
            Left = '<Left> ',
            Right = '<Right> ',
            C = '<C-…> ',
            M = '<M-…> ',
            D = '<D-…> ',
            S = '<S-…> ',
            CR = '<CR> ',
            Esc = '<Esc> ',
            ScrollWheelDown = '<ScrollWheelDown> ',
            ScrollWheelUp = '<ScrollWheelUp> ',
            NL = '<NL> ',
            BS = '<BS> ',
            Space = '<Space> ',
            Tab = '<Tab> ',
            F1 = '<F1>',
            F2 = '<F2>',
            F3 = '<F3>',
            F4 = '<F4>',
            F5 = '<F5>',
            F6 = '<F6>',
            F7 = '<F7>',
            F8 = '<F8>',
            F9 = '<F9>',
            F10 = '<F10>',
            F11 = '<F11>',
            F12 = '<F12>',
          },
        },
        spec = {
          { '<leader>s', group = '[s]plit' },
          { '<leader>f', group = '[f]ind' },
          { '<leader>q', group = '[q]uickreplace' },
          { '<leader>c', group = '[c]ode' },
          { '<leader>d', group = '[d]ebug' },
          { '<leader>b', group = '[b]uffer' },
          { '<leader>t', group = '[t]est' },
          { '<leader>h', group = '[h]unk', mode = { 'n', 'v' } },
        },
      }
    end,
  },
}
