-- Dump all custom neovim keymaps with descriptions as markdown
-- Intended to run after full init via VimEnter autocmd

local lines = {}
local function add(s)
	lines[#lines + 1] = s or ""
end

local function is_noise(desc, lhs)
	local d = vim.trim(desc)
	return d:match("^:help ")
		or d:match("^which_key_ignore")
		or d:match("^vim%.lsp%.buf%.")
		or d:match("^vim%.snippet%.")
		or d:match("^:%a?%l+$")
		or d:match("^Opens filepath or URI")
		or d:match("^Show diagnostics under")
		or d:match("^Jump to the .+ diagnostic")
		or lhs:match("^<C%-W>")
		or lhs:match("^<C%-T>")
end

local function collect_keymaps(mode)
	local maps = vim.api.nvim_get_keymap(mode)
	local result = {}
	for _, m in ipairs(maps) do
		if m.desc and m.desc ~= "" and not is_noise(m.desc, m.lhs) then
			local lhs = m.lhs:gsub(" ", "<Space>"):gsub("|", "\\|")
			result[#result + 1] = { lhs = lhs, desc = m.desc }
		end
	end
	table.sort(result, function(a, b)
		return a.lhs < b.lhs
	end)
	return result
end

local mode_names = {
	n = "Normal",
	v = "Visual",
	i = "Insert",
	x = "Visual (select)",
	o = "Operator-pending",
}

add("# Neovim Keymaps")
add("")
add("> Auto-generated by `just keymaps`. Do not edit manually.")
add(">")
add("> Buffer-local keymaps (LSP, git hunks) require an open file — use `<Space>fk` in nvim for the full list.")
add("")

for _, mode in ipairs({ "n", "v", "i", "x", "o" }) do
	local maps = collect_keymaps(mode)
	if #maps > 0 then
		add("**" .. (mode_names[mode] or mode) .. " mode:**")
		add("")
		add("| Key | Action |")
		add("|-----|--------|")
		for _, m in ipairs(maps) do
			add(string.format("| `%s` | %s |", m.lhs, m.desc))
		end
		add("")
	end
end

local out = table.concat(lines, "\n") .. "\n"
local f = io.open("/dev/stdout", "w")
if f then
	f:write(out)
	f:close()
end
vim.cmd("qa!")
