[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = "plugin augment-command -- enter"
desc = "Smart enter (open file or enter dir)"

[[mgr.prepend_keymap]]
on = ["o"]
run = "plugin augment-command -- open"
desc = "Smart open"

[[mgr.prepend_keymap]]
on = ["l"]
run = "plugin augment-command -- enter"
desc = "Smart enter (arrow right)"

[[mgr.prepend_keymap]]
on = ["h"]
run = "plugin augment-command -- leave"
desc = "Smart leave (arrow left)"

[[mgr.prepend_keymap]]
on = ["F"]
run = "plugin yafg"
desc = "Fuzzy find and grep (fzf+rg)"

[[mgr.prepend_keymap]]
on = ["/"]
run = "filter --smart"
desc = "Filter files (smart-case)"

[[mgr.prepend_keymap]]
on = ["b", "r"]
run = "cd ~/Repos/"
desc = "Go to [r]epos"

[[mgr.prepend_keymap]]
on = ["b", "g"]
run = "cd ~/Repos/quarry/glint"
desc = "Go to [g]lint"

[[mgr.prepend_keymap]]
on = ["b", "h"]
run = "cd ~/Repos/nephila"
desc = "Go to ne[p]hila"

[[mgr.prepend_keymap]]
on = ["b", "g"]
run = "cd ~/Repos/parry-guard"
desc = "Go to [p]arry-guard"

[[mgr.prepend_keymap]]
on = ["b", "m"]
run = "cd ~/Repos/mercury"
desc = "Go to [m]ercury"

[[mgr.prepend_keymap]]
on = ["b", "n"]
run = "cd @configPath@" # substituted at build time by builtins.replaceStrings
desc = "Go to [n]ix"

[[mgr.prepend_keymap]]
on = ["b", "l"]
run = "cd ~/Repos/logos"
desc = "Go to [l]ogos"

[[mgr.prepend_keymap]]
on = ["b", "e"]
run = "cd ~/Repos/solana-ibc"
desc = "Go to [e]ureka solana-ibc"

[[mgr.prepend_keymap]]
on = ["u", "a"]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = ["u", "g"]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = ["u", "G"]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = ["u", "d"]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = ["u", "D"]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = ["u", "A"]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = ["u", "r"]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = ["u", "R"]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"
